import { PROVIDER_TYPES, PROVIDER_STATUS } from './constants';

/**
 * Generate mock provider data with diverse entries for testing
 */
export const generateMockProviders = () => [
  {
    id: 1,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Hayat Regency',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 101,
    status: PROVIDER_STATUS.INACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: 33.5731, lng: -7.5898 },
    rating: 4,
    address: '123 Mohammed V Boulevard, Casablanca',
    phone: '+212 522 48 12 34',
    email: 'info@hayatregency.ma',
    description: 'Luxury hotel in the heart of Casablanca with modern amenities and excellent service.',
  },
  {
    id: 2,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'Wydad Academy',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 102,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5910, lng: -7.6337 },
    address: '456 Sports Complex Street, Casablanca',
    phone: '+212 522 35 67 89',
    email: 'academy@wydad.ma',
    pitchType: 'Natural Grass',
    description: 'Professional football training academy with state-of-the-art facilities.',
  },
  {
    id: 3,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Ibis Casablanca',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 103,
    status: PROVIDER_STATUS.DRAFT,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 33.5892, lng: -7.6114 },
    rating: 3,
    address: '789 Hassan II Boulevard, Casablanca',
    phone: '+212 522 27 45 67',
    email: 'reservations@ibiscasablanca.ma',
    description: 'Modern budget hotel with comfortable rooms and convenient location.',
  },
  {
    id: 4,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Mohamed 5',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 104,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5471, lng: -7.6589 },
  },
  {
    id: 5,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Dream Cars',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 105,
    status: PROVIDER_STATUS.INACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: 33.5950, lng: -7.6187 },
  },
  {
    id: 6,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Mohammed 5 International',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 106,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.3675, lng: -7.5898 },
  },
  {
    id: 7,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.LAUNDRY,
    name: 'Eco-Laundry',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 107,
    status: PROVIDER_STATUS.DRAFT,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 33.5861, lng: -7.6324 },
  },
  {
    id: 8,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.WATER_BOLT,
    name: 'Ice Company',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 108,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5996, lng: -7.6012 },
  },
  // Additional Casablanca entries for better testing
  {
    id: 31,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Four Seasons Casablanca',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 301,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 33.5641, lng: -7.5731 },
  },
  {
    id: 32,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Novotel Casablanca',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 302,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5823, lng: -7.5967 },
  },
  {
    id: 33,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Movenpick Casablanca',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 303,
    status: PROVIDER_STATUS.DRAFT,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 33.5701, lng: -7.6089 },
  },
  {
    id: 34,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'Raja Club Athletic',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 304,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 33.5789, lng: -7.6423 },
  },
  {
    id: 35,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'Casablanca Sports Complex',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 305,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5612, lng: -7.6201 },
  },
  {
    id: 36,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'Al Amal Football Academy',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 306,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5934, lng: -7.6145 },
  },
  {
    id: 37,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Stade Larbi Zaouli',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 307,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5523, lng: -7.6712 },
  },
  {
    id: 38,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Complexe Sportif Mohammed V',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 308,
    status: PROVIDER_STATUS.DRAFT,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 33.5445, lng: -7.6634 },
  },
  {
    id: 39,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Casa Express Transport',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 309,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5876, lng: -7.6234 },
  },
  {
    id: 40,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Royal Air Maroc',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 310,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 33.3700, lng: -7.5834 },
  },
  {
    id: 41,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Casa Taxis Premium',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 311,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5867, lng: -7.6012 },
  },
  {
    id: 42,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.LAUNDRY,
    name: 'Perfect Clean Casablanca',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 312,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5789, lng: -7.6123 },
  },
  {
    id: 43,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.LAUNDRY,
    name: 'Speed Wash Casa',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 313,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5634, lng: -7.6287 },
  },
  {
    id: 44,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.WATER_BOLT,
    name: 'Aqua Fresh Casa',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 314,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: false,
    coordinates: { lat: 33.5745, lng: -7.6045 },
  },
  {
    id: 45,
    dateAdded: '15/02/2025',
    type: PROVIDER_TYPES.WATER_BOLT,
    name: 'Hydro Plus Casablanca',
    comment: '',
    continent: 'Africa',
    country: 'Morocco',
    city: 'Casablanca',
    workspace: 315,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 33.5901, lng: -7.6178 },
  },
  // European entries
  {
    id: 9,
    dateAdded: '11/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Hotel Barcelona',
    comment: '',
    continent: 'Europe',
    country: 'Spain',
    city: 'Barcelona',
    workspace: 201,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 41.3851, lng: 2.1734 },
  },
  {
    id: 10,
    dateAdded: '11/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Camp Nou',
    comment: '',
    continent: 'Europe',
    country: 'Spain',
    city: 'Barcelona',
    workspace: 202,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 41.3809, lng: 2.1228 },
  },
  {
    id: 11,
    dateAdded: '11/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'La Masia Training',
    comment: '',
    continent: 'Europe',
    country: 'Spain',
    city: 'Barcelona',
    workspace: 203,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 41.3845, lng: 2.1186 },
  },
  {
    id: 12,
    dateAdded: '10/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'The Ritz London',
    comment: '',
    continent: 'Europe',
    country: 'United Kingdom',
    city: 'London',
    workspace: 301,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 51.5074, lng: -0.1278 },
  },
  {
    id: 13,
    dateAdded: '10/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Wembley Stadium',
    comment: '',
    continent: 'Europe',
    country: 'United Kingdom',
    city: 'London',
    workspace: 302,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 51.5560, lng: -0.2796 },
  },
  {
    id: 14,
    dateAdded: '10/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'London Black Cabs',
    comment: '',
    continent: 'Europe',
    country: 'United Kingdom',
    city: 'London',
    workspace: 303,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: 51.5074, lng: -0.1278 },
  },
  {
    id: 15,
    dateAdded: '09/02/2025',
    type: PROVIDER_TYPES.LAUNDRY,
    name: 'Paris Clean Service',
    comment: '',
    continent: 'Europe',
    country: 'France',
    city: 'Paris',
    workspace: 401,
    status: PROVIDER_STATUS.DRAFT,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 48.8566, lng: 2.3522 },
  },
  {
    id: 16,
    dateAdded: '09/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Stade de France',
    comment: '',
    continent: 'Europe',
    country: 'France',
    city: 'Paris',
    workspace: 402,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 48.9244, lng: 2.3601 },
  },
  // Asian entries
  {
    id: 17,
    dateAdded: '08/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Tokyo Grand Hotel',
    comment: '',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    workspace: 501,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 35.6762, lng: 139.6503 },
  },
  {
    id: 18,
    dateAdded: '08/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Tokyo Stadium',
    comment: '',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    workspace: 502,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: 35.6647, lng: 139.5273 },
  },
  {
    id: 19,
    dateAdded: '08/02/2025',
    type: PROVIDER_TYPES.WATER_BOLT,
    name: 'Tokyo Hydration Co',
    comment: '',
    continent: 'Asia',
    country: 'Japan',
    city: 'Tokyo',
    workspace: 503,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 35.6895, lng: 139.6917 },
  },
  {
    id: 20,
    dateAdded: '07/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'Beijing Training Center',
    comment: '',
    continent: 'Asia',
    country: 'China',
    city: 'Beijing',
    workspace: 601,
    status: PROVIDER_STATUS.DRAFT,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 39.9042, lng: 116.4074 },
  },
  {
    id: 21,
    dateAdded: '07/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Beijing Luxury Inn',
    comment: '',
    continent: 'Asia',
    country: 'China',
    city: 'Beijing',
    workspace: 602,
    status: PROVIDER_STATUS.INACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: 39.9042, lng: 116.4074 },
  },
  // North American entries
  {
    id: 22,
    dateAdded: '06/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Manhattan Plaza Hotel',
    comment: '',
    continent: 'North America',
    country: 'United States',
    city: 'New York',
    workspace: 701,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 40.7589, lng: -73.9851 },
  },
  {
    id: 23,
    dateAdded: '06/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Yankee Stadium',
    comment: '',
    continent: 'North America',
    country: 'United States',
    city: 'New York',
    workspace: 702,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: 40.8296, lng: -73.9262 },
  },
  {
    id: 24,
    dateAdded: '06/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'NYC Yellow Taxi',
    comment: '',
    continent: 'North America',
    country: 'United States',
    city: 'New York',
    workspace: 703,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: 40.7589, lng: -73.9851 },
  },
  {
    id: 25,
    dateAdded: '05/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'LA Galaxy Training',
    comment: '',
    continent: 'North America',
    country: 'United States',
    city: 'Los Angeles',
    workspace: 801,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 34.0522, lng: -118.2437 },
  },
  {
    id: 26,
    dateAdded: '05/02/2025',
    type: PROVIDER_TYPES.LAUNDRY,
    name: 'LA Quick Clean',
    comment: '',
    continent: 'North America',
    country: 'United States',
    city: 'Los Angeles',
    workspace: 802,
    status: PROVIDER_STATUS.DRAFT,
    views: 'closed',
    favorites: false,
    coordinates: { lat: 34.0522, lng: -118.2437 },
  },
  // South American entries
  {
    id: 27,
    dateAdded: '04/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Maracana Stadium',
    comment: '',
    continent: 'South America',
    country: 'Brazil',
    city: 'Rio de Janeiro',
    workspace: 901,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: -22.9068, lng: -43.1729 },
  },
  {
    id: 28,
    dateAdded: '04/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Copacabana Palace',
    comment: '',
    continent: 'South America',
    country: 'Brazil',
    city: 'Rio de Janeiro',
    workspace: 902,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'visible',
    favorites: true,
    coordinates: { lat: -22.9711, lng: -43.1822 },
  },
  {
    id: 29,
    dateAdded: '03/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'Buenos Aires FC',
    comment: '',
    continent: 'South America',
    country: 'Argentina',
    city: 'Buenos Aires',
    workspace: 1001,
    status: PROVIDER_STATUS.ACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: -34.6037, lng: -58.3816 },
  },
  {
    id: 30,
    dateAdded: '03/02/2025',
    type: PROVIDER_TYPES.WATER_BOLT,
    name: 'Buenos Aires Water',
    comment: '',
    continent: 'South America',
    country: 'Argentina',
    city: 'Buenos Aires',
    workspace: 1002,
    status: PROVIDER_STATUS.INACTIVE,
    views: 'invisible',
    favorites: false,
    coordinates: { lat: -34.6037, lng: -58.3816 },
  },
];
