import { PROVIDER_TYPES, PROVIDER_STATUS } from './constants';

/**
 * Generate mock provider data based on the screenshot
 */
export const generateMockProviders = () => [
  {
    id: 1,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Hayat Regency',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.INACTIVE,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.5731, lng: -7.5898 },
  },
  {
    id: 2,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.PITCH,
    name: 'Wydad Academy',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.ACTIVE,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.5910, lng: -7.6337 },
  },
  {
    id: 3,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.HOTEL,
    name: 'Ibis Casablanca',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.DRAFT,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.5892, lng: -7.6114 },
  },
  {
    id: 4,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.STADIUM,
    name: 'Mohamed 5',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.ACTIVE,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.5471, lng: -7.6589 },
  },
  {
    id: 5,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Dream Cars',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.INACTIVE,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.5950, lng: -7.6187 },
  },
  {
    id: 6,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Mohammed 5 International',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.ACTIVE,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.3675, lng: -7.5898 },
  },
  {
    id: 7,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.LAUNDRY,
    name: 'Eco-Laundry',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.DRAFT,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.5861, lng: -7.6324 },
  },
  {
    id: 8,
    dateAdded: '12/02/2025',
    type: PROVIDER_TYPES.TRANSPORT,
    name: 'Ice Company',
    comment: '',
    country: 'Africa',
    city: 'Morocco',
    workspace: 'Casablanca',
    status: PROVIDER_STATUS.ACTIVE,
    views: 12,
    favorites: 0,
    coordinates: { lat: 33.5996, lng: -7.6012 },
  },
];
